import "./globals.css";
import { Lato } from "next/font/google";
import Header from "@/app/components/Header";
const lato = Lato({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  style: ["italic", "normal"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <div>
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
