import ImgTope from "../components/ImgTope";

export const metadata = {
  title: "Market",
  description: "Generated by create next app",
};

export default function MarketLayer({ children }) {
  return (
    <div>
      <ImgTope />
      {children}
    </div>
  );
}
